### ISSUE TITLE
Make buffer around country polygons bigger

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#465]
Buffer for countries should be around `100m` for the border. Should be adaptable (setting?)

Update the [countries boundaries](https://osm.wno-edv-service.de/boundaries/) before and check again

**Comment by das-g** [comment]
> Should be adaptable (setting?)

Do you mean a deployment-specific setting or an export option the user can choose for each order they make?

**Comment by hixi** [comment]
No, technical, a setting that can be changed per deployment.

**Comment by das-g** [comment]
c4e4a7cf70e4cb255b71b1d4bc98e04e24a71c5f (merged with PR #485) introduced a buffer of 500m around country areas.

Closing as resolved.

**Comment by hixi** [comment]
@das-g Should this be reopened since the buffer requested has been 100m and not 500m?

**Comment by das-g** [comment]
> Should this be reopened since the buffer requested has been 100m and not 500m?

For counties it probably doesn't matter too much.

But because the sub-country administrative areas we also offer have their boundary on the coastline (if any) rather than at the line between national and international sea, I'd leave the buffer width at 500&nbsp;m, so that stuff in the sea near the coast won't be almost completely omitted.

Reopening issue to have this discussed with stakeholders.
