### ISSUE TITLE
attribute "city" of layer "address_p" should use OSM tag "addr:city", not "addr:place"

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#574]
Use OSM tag `addr:city` rather than `addr:place` for attribute `city` of layer `address_p` in all SQL scripts where that attribute is set.

---
##### original description
~~[Currently, we put the value](https://github.com/geometalab/osmaxx-frontend/blob/86cb6871ed7b02b3aa9160db0a5d079ccd1e5aee/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/address/010_address.sql#L35) of [OSM tag `addr:place=*`](http://wiki.openstreetmap.org/wiki/Key:addr:place) into the `city` attribute of layer `address_p`.~~

~~I think if present, tags [`addr:city=*`, ` is_in:city=*`, `addr:hamlet=*` and `addr:suburb=*`](http://wiki.openstreetmap.org/wiki/Key:addr) should be used instead (if any of them present, precedence if several present TDB.)~~

~~If none of them are present, we can still fall back to `addr:place=*`. Although, we might only want to do that if `addr:street=*` is present, so that the `addr:place=*` hasn't already been used in attribute `street`.~~

**Comment by sfkeller** [comment]
I think line 35 `"addr:place" as city,` is an error since addr:place is handled in target attribute street. It should be `addr:city" as city,`.

But pls. remember: address_p should currently mainly used to handle house numbers e.g. for the map. I would like to postpone more enhancements until project OSM2Names comes out with new insights about addresses in OSM (about August 2016).
